### ISSUE TITLE
Video Recording Feature

### ISSUE THREAD

**Issue by jaye-heglund** [osipychev/ctf_public#5]
Want to specify somewhere in a sim for the environment to take a video and output the raw video to a directory.

**Comment by skim0119** [comment]
I'm not sure about the video, but I use 'imageio' package for exporting out to .gif file.
It needs separate package installation.

Here is a code snippet I used to render. The downside is it renders the image in graphics also, so it slow down the program. I would only use rendering when I'm not training.
```py
import imageio
import gym, gym_cap

env = gym.make("cap-v0").unwrapped
env.reset()

frames = []
for step in range(max_ep+1):
    frames.append(env.render(mode='rgb_array'))
    env.step()
...
...

imageio.mimsave(RENDER_PATH+'/series__render.gif', frames)
```
The gif file with this method is also uncompressed, so it needs post-compression.

**Comment by osipychev** [comment]
Skin is right. There is lots of off the shelf tools to do that. I often just save it renders as a raw image. We want to stick to original gym functionality.
