### ISSUE TITLE
Rendering the environment doesn't accurately represent the vision radius of the agent

### ISSUE THREAD

**Issue by jaye-heglund** [osipychev/ctf_public#6]
![radius](https://user-images.githubusercontent.com/28881853/51864325-14abec00-2309-11e9-8511-be927e4f74bc.PNG)

In this example, I set the blue team's vision radius to be 11 so the env was fully observable, but this was not reflected in the bottom right rendering.

**Comment by skim0119** [comment]
Did you change the constant UGV_RANGE in const.py file?

**Comment by jaye-heglund** [comment]
No, I wasn't aware that you could change that as part of const.py.  
If that fixes the rendering, I can close the issue, but we need better documentation for the environment so that anybody using the environment can know this.

**Comment by skim0119** [comment]
I agree. I think README should include more clear description about const.py configuration.
